version: "3.3"

services:
  
  app:
    container_name: api
    image: pepegrigorchenko/cursor-games-api
    build:
      context: https://github.com/PyotrGrogorchenko/cursor-games-api.git#main:Dockerfile.dev
      #context: .
      #dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    #environment:
    #  NODE_ENV: development
    #   - .:/app
    restart: always
    networks:
      - main
    depends_on:
      - db      
  
  db:
    container_name: api_db
    hostname: db
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - main

volumes:
  db-data:      
networks:
  main:
    driver: bridge   