version: "3.3"

services:
  
  web:
    container_name: api-web
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: always
    networks:
      - main
    depends_on:
      - db      
  
  db:
    container_name: api-db
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: games
    ports:
      - 5432:5432
    volumes:
     - db-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - main

volumes:
  db-data:      
networks:
  main:
    driver: bridge  